spring:
  config:
    import:
      - db-core.yml

jwt:
  key-id: asj
  secret: duckads
  access-token-validity-in-seconds: 3600    # second, 1H
  refresh-token-validity-in-seconds: 86400    # second, 24H